// styles/navbar.js
export const navbarStyles = {
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    backdropFilter: 'blur(18px)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderBottom: '1px solid #e5e7eb',
  },
  headerContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '14px 24px',
    display: 'grid',
    gridTemplateColumns: '1.1fr auto 1.1fr',
    alignItems: 'center',
    columnGap: '24px',
  },
  navLeft: {
    display: 'flex',
    gap: '24px',
    alignItems: 'center',
  },
  navRight: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '16px',
    alignItems: 'center',
  },
  navCenter: {
    display: 'flex',
    justifyContent: 'center',
  },
  brandText: {
    fontSize: '28px',
    fontWeight: 800,
    letterSpacing: 0.5,
    color: '#1d4ed8',
  },
  navLink: {
    background: 'none',
    border: 'none',
    padding: 0,
    fontSize: '15px',
    color: '#4b5563',
    cursor: 'pointer',
    fontWeight: 500,
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px 12px',
    borderRadius: '999px',
    border: '1px solid #e5e7eb',
    fontSize: '14px',
    color: '#6b7280',
    backgroundColor: '#f9fafb',
  },
  navPrimaryButton: {
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    padding: '8px 22px',
    borderRadius: '999px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 8px 22px rgba(37,99,235,0.35)',
  },
  walletInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  walletAddress: {
    backgroundColor: '#eff6ff',
    padding: '8px 14px',
    borderRadius: '999px',
    fontFamily: 'monospace',
    fontSize: '13px',
    fontWeight: 600,
    color: '#1d4ed8',
  },
  adminBadge: {
    backgroundColor: '#fbbf24',
    color: '#78350f',
    padding: '6px 12px',
    borderRadius: '999px',
    fontSize: '13px',
    fontWeight: 600,
  },
};
